
name: Build Pyodide wheel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events 
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build for pyodide 0.21.0
  Pyodide_test_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.2
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.1.14
    - run: bash ./setup_test_env.sh
